# Generated by Django 5.2.6 on 2026-05-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP Procurement & Fuel Flat File"),
                            ("UTILITY_BILL", "Utility Portal Monthly CSV"),
                            ("UTILITY_METER", "Smart Meter Hourly Interval Stream"),
                            ("TRAVEL", "Concur Corporate Travel Expense JSON"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by_email",
                    models.CharField(default="analyst@breatheesg.com", max_length=100),
                ),
                ("row_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True, null=True)),
                (
                    "tenant_id",
                    models.CharField(default="client_enterprise_alpha", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=50)),
                ("unit", models.CharField(max_length=20)),
                (
                    "factor_kg_co2e",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("scope", models.CharField(max_length=10)),
                ("source", models.CharField(max_length=150)),
                ("year", models.IntegerField()),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "unique_together": {("activity_type", "unit", "region", "year")},
            },
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField()),
                ("raw_data", models.TextField()),
                ("has_error", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ingestion.rawupload",
                    ),
                ),
            ],
            options={
                "unique_together": {("upload", "line_number")},
            },
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("ERROR", "Error"), ("WARNING", "Warning")],
                        max_length=10,
                    ),
                ),
                ("issue_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_issues",
                        to="ingestion.rawrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(default="client_enterprise_alpha", max_length=50),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1: Direct Combustion"),
                            ("SCOPE_2", "Scope 2: Purchased Utilities"),
                            ("SCOPE_3", "Scope 3: Broader Value Chain"),
                        ],
                        max_length=10,
                    ),
                ),
                ("scope_category", models.CharField(max_length=150)),
                ("activity_type", models.CharField(max_length=50)),
                ("activity_date", models.DateField()),
                ("reporting_period", models.CharField(max_length=7)),
                (
                    "facility_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("country_code", models.CharField(default="IND", max_length=3)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "factor_value_used",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("emission_factor_source", models.CharField(max_length=150)),
                ("co2e_kg", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("SUSPICIOUS", "Flagged Anomaly"),
                            ("APPROVED", "Approved & Sealed"),
                            ("REJECTED", "Archived From Active Queue"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "anomaly_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "QUANTITY_SPIKE",
                                "Consumption spike >2.5x facility baseline",
                            ),
                            ("NEGATIVE_VALUE", "Impossible negative ledger quantity"),
                            (
                                "MISSING_FACILITY",
                                "Opaque or missing facility location identity",
                            ),
                            (
                                "FUTURE_DATE",
                                "Activity registration date falls into future space",
                            ),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("anomaly_details", models.TextField(blank=True, null=True)),
                ("validation_bypassed", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by_email",
                    models.CharField(default="analyst@breatheesg.com", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_activities",
                        to="ingestion.rawrecord",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["review_status", "-created_at"],
                        name="ingestion_n_review__454d17_idx",
                    )
                ],
            },
        ),
    ]
