# Generated by Django 5.2.6 on 2026-05-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normalizedactivity",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("SUSPICIOUS", "Flagged Anomaly"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
